version: '3.2'

services:
  '5.4-centos6': &base_image
    ulimits: { core: 99999999999 }
    stdin_open: true
    tty: true
    volumes: [ '../../:/build_src' ]
    cap_add: [ SYS_PTRACE ]
    image: 'datadog/dd-trace-ci:php-5.4_centos-6'
  '5.5-centos6': { <<: *base_image, image: 'datadog/dd-trace-ci:php-5.5_centos-6' }
  '5.6-centos6': { <<: *base_image, image: 'datadog/dd-trace-ci:php-5.6_centos-6' }
  '7.0-centos6': { <<: *base_image, image: 'datadog/dd-trace-ci:php-7.0_centos-6' }
  '7.1-centos6': { <<: *base_image, image: 'datadog/dd-trace-ci:php-7.1_centos-6' }
  '7.2-centos6': { <<: *base_image, image: 'datadog/dd-trace-ci:php-7.2_centos-6' }
  '7.3-centos6': { <<: *base_image, image: 'datadog/dd-trace-ci:php-7.3_centos-6' }
  '7.4-centos6': { <<: *base_image, image: 'datadog/dd-trace-ci:php-7.4_centos-6' }
  '8.0-centos6': { <<: *base_image, image: 'datadog/dd-trace-ci:php-8.0_centos-6' }

  alpine:
    image: ${ALPINE_IMAGE}
    working_dir: /datadog
    volumes:
      - ../../:/datadog
    environment:
      PHP_PACKAGE: ${PHP_PACKAGE}
      PACKAGE_TYPE: ${PACKAGE_TYPE}
      SIGNALFX_ENDPOINT_HOST: request-replayer
      SIGNALFX_ENDPOINT_PORT: 80
      SIGNALFX_TRACE_DEBUG: 'false'
    depends_on:
      - request-replayer

  centos:
    image: ${DOCKER_IMAGE}
    working_dir: /datadog
    volumes:
      - ../../:/datadog
    environment:
      SIGNALFX_ENDPOINT_HOST: request-replayer
      SIGNALFX_ENDPOINT_PORT: 80
      SIGNALFX_TRACE_DEBUG: 'false'
    depends_on:
      - request-replayer

  debian:
    image: ${DOCKER_IMAGE}
    working_dir: /datadog
    volumes:
      - ../../:/datadog
    environment:
      SIGNALFX_ENDPOINT_HOST: request-replayer
      SIGNALFX_ENDPOINT_PORT: 80
      SIGNALFX_TRACE_DEBUG: 'false'
    depends_on:
      - request-replayer

  tar_gz:
    image: debian:buster
    working_dir: /datadog
    volumes:
      - ../../:/datadog

  request-replayer:
    image: datadog/dd-trace-ci:php-request-replayer
